### ISSUE TITLE
General Phenopackets Scope & Genetic Data Comments

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#236] opened 2020-07-22 20:27 UTC
Comment:
> The first comment is about the scope of this proposed standard. This data exchange format was originally developed for rare and undiagnosed diseases, and this format is matured for description of phenotype of rare disease patients. But this format is generally biased towards the rare disease description, and has room for improvement for “common/complex disease”. The required fields in this format are for rare disease, and are different from those for common/complex diseases; especially, the fields defined in the section 6.2 Family (p.9) are unnecessary for common/complex disease, and should be optional. Phenotype descriptions are very diverse from rare disease to common/complex disease. Flexibility is important in phenotypic description incorporating many existing standards and ontologies. The second comment is about the standard for description of genetic data. This proposed standard is a format for phenotypic data exchange but it contains genetic data description. Is consistency
with the other relevant standards in ISO properly coordinated? The genetic data description itself is very complex. Recently, a number of non-coding variants have been found, and it has become well known that they are related to diseases. According to this draft, non-coding variants will be described as just variant but some of non-coding variants can be described by non-coding gene with HGNC symbol. The genetic data description should also follow the standard.

This comment may require some additional discussion when the project team launches. I'm not familiar with what the relevant ISO standards would be.

**Comment by pnrobinson** [comment] 2020-11-03 19:55
@lindsmith  Is this still open? I think that our standards for variants can deal easily with non-coding data, but this is not the focus of phenopackets and we will leave heavy lifting to VRS, while providing a few fields for convenience with other formats (HGVS, VCF-ish). I think we could close this issue unless there are objections. @julesjacobsen

**Comment by lindsmith** [comment] 2020-11-03 20:32
@pnrobinson I think there are two parts to this comment: 1) Changing some required fields to optional to allow for flexibility with domains beyond rare disease and 2) incorporating VRS.

For 1), I have requested from the ISO project team which fields they're specifically referring to (beyond the family piece mentioned) but haven't heard anything. I suppose we could review on our end and make sure the requirement levels still hold up. For 2), I agree the variant heavy-lifting should be left to VA and VR, but it would be good to have VR referenced as one of those fields if we can. I recall @julesjacobsen mentioning something about adding in the VRS hash as an element?

**Comment by julesjacobsen** [comment] 2020-11-05 09:49
> But this format is generally biased towards the rare disease description, and has room for improvement for “common/complex disease”. The required fields in this format are for rare disease, and are different from those for common/complex diseases; especially, the fields defined in the section 6.2 Family (p.9) are unnecessary for common/complex disease, and should be optional. 

True and this is by design but the `Family` message is entirely optional. The common/complex disease case is being addressed in the v2 update.

>  Phenotype descriptions are very diverse from rare disease to common/complex disease. Flexibility is important in phenotypic description incorporating many existing standards and ontologies.

Indeed. I'm not sure if this is meant as a positive or negative statement. The phenopacket allows any existing ontology to be used, but we have examples in some places where the most generally relevant ontology is indicated e.g. HPO for human rare disease phenotype descriptions or HGNC identifiers for human gene identifiers/names. 

> Recently, a number of non-coding variants have been found, and it has become well known that they are related to diseases. According to this draft, non-coding variants will be described as just variant but some of non-coding variants can be described by non-coding gene with HGNC symbol. The genetic data description should also follow the standard.

The standard allows description of variation using any one of VCF, SPDI, HGVS or ISCA nomenclature. These are capable of describing a position or region of the genome irrespective of whether it is located in a coding or non-coding region. It also allows linking to any of the standard high-throughput sequencing files for a sample to software can perform their own analysis over an entire genome if required.

**Comment by julesjacobsen** [comment] 2020-11-05 09:49
@lindsmith yes, I did mention this. Need to add it now!

**Comment by pnrobinson** [comment] 2021-03-26 13:41
@lindsmith @julesjacobsen I think we have addressed these items in the new documentation. Can we close this issue?

**Comment by lindsmith** [comment] 2021-03-26 13:44
@pnrobinson Yes, I think we're good to close!

**Closed** 2021-03-31 13:07 UTC
Labels: ISO, documentation
